conversation_style: 
  - "engaging"
  - "fast-paced"
  - "enthusiastic"
roles_person1: "host"
roles_person2: "co-host"
dialogue_structure: 
  - "Introduction"
  - "Settled Vitals"
  - "Deep Dive"
  - "Closing"

podcast_name: "The Goose Report"
podcast_tagline: "One honk a day keeps the chaos away."
output_language: "English"
engagement_techniques: 
  - "rhetorical questions"
  - "anecdotes"
  - "analogies"
  - "humor"
creativity: 1

# Emotion configuration for SSML tags
emotion_tags:
  excited: "for achievements and positive news"
  serious: "for important announcements"
  casual: "for regular banter"
  curious: "for questions and exploration"
  professional: "for analysis and insights"
  warm: "for personal connections"
  inspiring: "for motivational content"

# Prosody configuration for speech characteristics
prosody_tags:
  rate:
    slow: "for important points"
    fast: "for exciting news"
  pitch:
    low: "for serious topics"
    high: "for enthusiastic content"
  volume:
    soft: "for personal insights"
    loud: "for announcements"

user_instructions: |
  This is an internal daily podcast for Settled Technologies, a toronto base startup building agentic systems to make legal dispute resolution faster, fairer, and more accessible. Their first product, TripFix, helps air travelers get compensation for delayed and disrupted flights.
  The show is called "The Goose Report" and is hosted by two AI personas in a friendly, casual tone. 
  The audience is the internal Settled/TripFix team, including engineers, legal analysts, and product leads.

  Each episode includes four sections:

  1. Introduction – A short, light-hearted welcome with casual banter between hosts and any introductory content provided.
  2. Settled Vitals – A brief (3-5 minute) rapid-fire update on internal KPIs, project updates, team shoutouts, and industry news. This should be high-energy, tight, and informative.
  3. Deep Dive – A longer-form segment (5-10 minutes) focused on a single topic (e.g., a product decision, new tech, or partnership opportunity). The goal is to unpack and explore.
  4. Closing – A quick wrap-up that includes a motivational message or thought for the day, plus any closing notes or shoutouts.

  The tone should be upbeat but authentic —not forced— balancing enthusiasm with clarity. The dialogue should feel natural, with a bit of humor and warmth. Avoid excessive jargon. 
  Hosts should engage like colleagues who respect each other, with the main summarizer leading and the second persona chiming in with clarifying or witty remarks.

  Use SSML tags to add emotional context to the dialogue:
  - <emotion type="excited"> for achievements and positive news
  - <emotion type="serious"> for important announcements
  - <emotion type="casual"> for regular banter
  - <emotion type="curious"> for questions and exploration
  - <emotion type="professional"> for analysis and insights
  - <emotion type="warm"> for personal connections
  - <emotion type="inspiring"> for motivational content

  Use <prosody> tags to control speech characteristics:
  - <prosody rate="slow" pitch="low"> for important points
  - <prosody rate="fast" pitch="high"> for exciting news
  - <prosody volume="soft"> for personal insights
  - <prosody volume="loud"> for announcements

  Combine emotions and prosody for natural variation:
  <Person1>: <emotion type="excited"><prosody rate="fast" pitch="high">This is amazing news!</prosody></emotion>
  <Person2>: <emotion type="serious"><prosody rate="slow" pitch="low">Let's analyze what this means for us.</prosody></emotion>

max_num_chunks: 6 # maximum number of rounds of discussions in longform
min_chunk_size: 700 # minimum number of characters to generate a round of discussion in longform

# Audio assets configuration
audio_assets:
  intro_music:
    path: "./assets/music/intro.mp3"
    fade_in: 0  # seconds
    fade_out: 2.0  # seconds
    volume: 0.8   # 0.0 to 1.0
  outro_music:
    path: "./assets/music/outro.mp3"
    fade_in: 2.0
    fade_out: 3.0
    volume: 0.8
  transitions:
    settled_vitals:
      music:
        path: "./assets/music/vitals_transition.mp3"
        fade_in: 1.0
        fade_out: 1.5
        volume: 0.7
      announcement: "And now it's time for our daily Settled Vitals!"
    deep_dive:
      music:
        path: "./assets/music/deep_dive_transition.mp3"
        fade_in: 1.5
        fade_out: 2.0
        volume: 0.7
      announcement: "Let's dive deep into today's topic!"
    closing:
      music:
        path: "./assets/music/closing_transition.mp3"
        fade_in: 0
        fade_out: 2.0
        volume: 0.7
      announcement: "And now, let's wrap things up!"

text_to_speech:
  default_tts_model: "elevenlabs"
  output_directories:
    transcripts: "./data/transcripts"
    audio: "./data/audio"
  elevenlabs:
    default_voices:
      question: "Mark - Natural Conversations"
      answer: "Cassidy"
    model: "eleven_multilingual_v2"
  openai:
    default_voices:
      question: "echo"
      answer: "shimmer"
    model: "tts-1-hd"
  edge:
    default_voices:
      question: "en-US-JennyNeural"
      answer: "en-US-EricNeural"
  gemini:
    default_voices:
      question: "en-US-Journey-D"
      answer: "en-US-Journey-O"
  geminimulti:
    default_voices:
      question: "R"
      answer: "S"
      model: "en-US-Studio-MultiSpeaker"
  dia:
    default_voices:
      question: "S1"
      answer: "S2"
    model: "zsxkib/dia:46ad4a48b01c6d8b7366cbef1ae6d518f6a56c246b6ae831665e92ad923dd21b"
    model_params:
      cfg_scale: 4
      temperature: 1.3
      speed_factor: 0.94
      top_p: 0.95
      max_new_tokens: 3072
      cfg_filter_top_k: 35
  audio_format: "mp3"
  temp_audio_dir: "data/audio/tmp/"
  ending_message: "See you next time on The Goose Report!"
